import 'package:drift/drift.dart';

// ── Folders ───────────────────────────────────────────────────────────────────

/// @DataClassName avoids collision with the domain entity `Folder`.
@DataClassName('FolderData')
class Folders extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text().withLength(min: 1, max: 120)();

  /// Category enum stored as string (e.g. 'work', 'education').
  TextColumn get category => text().withDefault(const Constant('other'))();

  /// 6-digit hex colour without '#', e.g. '7C3AED'.
  TextColumn get colorHex => text().withLength(min: 6, max: 6)();

  /// Lucide icon name string, e.g. 'briefcase'.
  TextColumn get iconName => text().withDefault(const Constant('folder'))();

  /// True for the virtual "Inbox" folder seeded at migration v1.
  BoolColumn get isInbox => boolean().withDefault(const Constant(false))();

  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}

// ── Meetings ──────────────────────────────────────────────────────────────────

/// @DataClassName avoids collision with the domain entity `Meeting`.
@DataClassName('MeetingData')
class Meetings extends Table {
  IntColumn get id => integer().autoIncrement()();

  /// UUID-based draft ID generated by StartRecording use-case.
  TextColumn get draftId => text().unique()();

  IntColumn get folderId =>
      integer().references(Folders, #id, onDelete: KeyAction.setDefault)();

  TextColumn get title => text().withLength(min: 1, max: 200)();
  TextColumn get audioPath => text()();
  IntColumn get durationSeconds => integer().withDefault(const Constant(0))();
  TextColumn get transcript => text().withDefault(const Constant(''))();
  TextColumn get summary => text().withDefault(const Constant(''))();

  /// PipelineState stored as string: pending/transcribing/summarizing/done/failed.
  TextColumn get pipelineState =>
      text().withDefault(const Constant('pending'))();

  /// BCP-47 code auto-detected by Whisper, e.g. 'fr', 'ar'. Empty until done.
  TextColumn get detectedLanguage =>
      text().withDefault(const Constant(''))();

  /// FK to CalendarEvents if this meeting was recorded against a scheduled event.
  IntColumn get linkedEventId => integer().nullable()();

  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();

  @override
  List<Set<Column>> get uniqueKeys => [];

  @override
  List<Index> get indexes => [
        Index('meetings_folder_idx', 'CREATE INDEX meetings_folder_idx ON meetings (folder_id)'),
        Index('meetings_created_idx', 'CREATE INDEX meetings_created_idx ON meetings (created_at DESC)'),
      ];
}

// ── Calendar events ───────────────────────────────────────────────────────────

/// @DataClassName avoids collision with the domain entity `CalendarEvent`.
@DataClassName('CalendarEventData')
class CalendarEvents extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text().withLength(min: 1, max: 200)();

  IntColumn get folderId =>
      integer().references(Folders, #id, onDelete: KeyAction.setDefault)();

  DateTimeColumn get startsAt => dateTime()();
  DateTimeColumn get endsAt => dateTime()();

  /// Minutes before startsAt to fire the local notification.
  IntColumn get reminderMinutes =>
      integer().withDefault(const Constant(15))();

  /// ID used with flutter_local_notifications so it can be cancelled.
  IntColumn get notificationId => integer()();

  /// Set after a meeting is recorded against this event ([IP-0039]).
  IntColumn get linkedMeetingId => integer().nullable()();

  @override
  List<Index> get indexes => [
        Index('events_starts_idx', 'CREATE INDEX events_starts_idx ON calendar_events (starts_at)'),
      ];
}
